### ISSUE TITLE
As a user, I want the camera go to functionality to work consistently as expected

### ISSUE THREAD

**Issue by erheine1** [mfthomps/CyberCIEGE-port-to-Unity3d#112]
- The UI now has buttons to go to previous of a type, which should be implemented
- Cycling through computers should not go to devices and vice versa (currently they use shared ComponentBehavior logic)
- Cycling through computers/devices requires an extra click when the last item has been reached (if two items, it takes three clicks to go back to the first item instead of two)

**Comment by CowboyCoderForever** [comment]
Note: issue/160 branch has some code in place to assist this.
