### ISSUE TITLE
[bug] ArgumentOutOfRangeException: Hour, Minute, and Second parameters describe an un-representable DateTime.

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#121]
I've seen this happen a few times, but haven't been able to replicate 100%.

Something about cycling the Play/Pause state in the Introduction Scenario.

> ArgumentOutOfRangeException: Hour, Minute, and Second parameters describe an un-representable DateTime.
> System.DateTime.TimeToTicks (System.Int32 hour, System.Int32 minute, System.Int32 second) (at <9577ac7a62ef43179789031239ba8798>:0)
> System.DateTime..ctor (System.Int32 year, System.Int32 month, System.Int32 day, System.Int32 hour, System.Int32 minute, System.Int32 second) (at <9577ac7a62ef43179789031239ba8798>:0)
> GameStatusScript.UpdateStatus (System.String message) (at Assets/Code/GameStatusScript.cs:78)

**Comment by erheine1** [comment]
I didn't notice this issue before, but I fixed this in another commit:
https://github.com/mfthomps/CyberCIEGE-port-to-Unity3d/commit/a915ccd164bb59fee973da27587c7cf84cbe812b#diff-ae8d12aebf6c2d8e5112d6ef612d7741fcebf8d18d36553bdef51b23515169aa
