### ISSUE TITLE
I want to see the characters walk around the office space

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#13]
The game commands where the characters should walk to, given the coordinate system of the space. Use this information to calculate a path and instruct the character to walk to the destination.

I assume NavMeshAgent and a NavMesh will be involved here.

Presumably the `UserBehavior.cs` is involved?

- [x] Female User
- [x] IT Staff
- [x] Guard Staff
- [x] Setup workspace furniture as NavMesh obstacles.
- [ ] Don't animate the characters if the Game is paused

**Comment by ghost** [comment]
Notes so far:

`UserBehavior` looked promising at first, but as far as I can tell it does not receive any position commands from the `IPCManagerScript`. It seems like the only time it deals with position is the initial placement of users, when it reads the `PosIndex` attribute from the .sdf file. 

All the messages received by `UserBehavior` are just generic status packets like the following: 

`<user_status>
	<user><name>Email Server</name>
	<thought>hmmmm</thought>
	<training>0</training>
	</user>
	<user><name>Web Server</name>
	<thought>hmmmm</thought>
	<training>0</training>
	</user>
	<user><name>Curly</name>
	<thought>It would be nice to have a computer I could work on.</thought>
	<training>70</training>
		<goal><name>Modify BortSoft Data</name><status>fail</status></goal>
		<goal><name>Read Curly's E-Mail</name><status>fail</status></goal>
	</user>
	<user><name>Moe</name>
	<thought>It would be nice to have a computer I could work on.</thought>
	<training>70</training>
		<goal><name>Modify BortSoft Data</name><status>fail</status></goal>
		<goal><name>Read Moe's E-Mail</name><status>fail</status></goal>
	</user>
	<user><name>Attacker</name>
	<thought>I can't wait to go home.</thought>
	<training>0</training>
	</user>
</user_status>`

I checked the rest of the packets in `IPCManagerScript` while the clock was running during the Intro Scenario and I wasn't purchasing computers, so Curly and Moe should've been commanded to roam around the office. I didn't see any sort of positional commands/data being sent during this. 

Curiously, I did see some numbers in the tooltip packets that aren't being used by the `ToolTipScript` (or anywhere else), but I don't think those numbers are meant for Curly and Moe: 

`<tool_tip><text>Select the Objectives tab to view your objectives.</text><x>490</x><y>160</y><x_to>640</x_to><y_to>80</y_to></tool_tip>
UnityEngine.Debug:Log(Object)
IPCManagerScript:Update() (at <a href="Assets/Code/IPCManagerScript.cs" line="63">Assets/Code/IPCManagerScript.cs:63</a>)`

`<tool_tip><text>Select the "OFFICE" tab to return to the office</text><x>200</x><y>100</y><x_to>100</x_to><y_to>90</y_to></tool_tip>
UnityEngine.Debug:Log(Object)
IPCManagerScript:Update() (at <a href="Assets/Code/IPCManagerScript.cs" line="63">Assets/Code/IPCManagerScript.cs:63</a>)`

`<tool_tip><text>Curly needs a computer. Buy him one using the Buy Button.</text><x>500</x><y>500</y><x_to>950</x_to><y_to>660</y_to></tool_tip>
UnityEngine.Debug:Log(Object)
IPCManagerScript:Update() (at <a href="Assets/Code/IPCManagerScript.cs" line="63">Assets/Code/IPCManagerScript.cs:63</a>)`

I'm looking through the rest of the scripts in the project to see if I'm missing something obvious, but so far I don't see where the game is sending out those position commands.

**Comment by CowboyCoderForever** [comment]
I poked through the original code briefly and didn't see anything about sending the User's go-to position to Unity. So perhaps this functionality isn't supported yet.

**Comment by CowboyCoderForever** [comment]
- [x] If a User has a computer go to it.
- [x] If a User is at their own (?) computer
     - [x]   User should sit down
     - [x]   If the User is not achieving Goals or is unhappy (unproductive?), then bang on keyboard
     - [x]  Else, the user should type
- [x] Else, the User should wander
     - [x]   Find another interesting location and path there.

**Comment by CowboyCoderForever** [comment]
Closing in anticipation of opening other issues.
