### ISSUE TITLE
As a user, I want to have the camera viewing a useful location when the scenario is started.

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#15]
The scenario should start with the camera viewing something useful. Run the original CC Game and watch how the camera flies in.

**Comment by mfthomps** [comment]
The server now creates a viewpoints.sdf file containing the camera viewpoints defined for the scenario.  Unless "skipTab" is defined, these viewpoints used when the player tabs between viewpoints.  The viewpoints are also named in a new "cameraToViewpoint" event that includes the desired index number.
There is also a camerToUser event that names a user, a boolean controlling whether the camera should face the user, and an optional angle and zoom.  These result from game triggers in the server.  See the patches scenario and the password scenario for examples of their use.  The Patches scenario has a unique "ForceCamera" setting in the Options of the viewpoints.sdf.  This forces the camera to always track to the last user named by a cameraToUser event.  It is how the character is tracked in Patches as he walks back and forth.

**Comment by CowboyCoderForever** [comment]
Maybe need to take the Viewpoint definition and divide by "GRID_SIZE" (OG has GRID_SIZE = 3).
