### ISSUE TITLE
[bug] Buying a computer doesn't actually cost any money.

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#179]
Buy a computer and notice the Funds don't change. In the OG, it does.

**Comment by erheine1** [comment]
@mfthomps Should this happen as part of the server's <componentEvent><buy> event?  Or should I send a separate cost event?

**Comment by mfthomps** [comment]
I just tested this and say my funds decrease when buying a computer.

**Comment by erheine1** [comment]
Yup, I see this, too, now.  I'll close the issue.
