### ISSUE TITLE
I want the male worker to look like the one in the original game

### ISSUE THREAD

**Issue by phfatmonkey** [mfthomps/CyberCIEGE-port-to-Unity3d#185]
![image](https://user-images.githubusercontent.com/3812933/106969967-c81df700-6700-11eb-8c3f-7c04ddadc883.png)

**Comment by CowboyCoderForever** [comment]
I just noticed that the avatars change based on which Office is loaded. I guess the Physical Security scenario is a military building and gets military looking people?

If you can whip up the prefabs for all the avatars, I can refactor the code to use them in the right scenarios.
