### ISSUE TITLE
[bug] Selecting a World Object (properties displayed in the Property Panel) stops game time

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#186]
It appears if you select something in the game (like a User or Computer), the simulated game time pauses, until you deselect it.

I know this is supposed to happen when opening regular dialogs, but probably not when a player just selects something in the office.

**Comment by erheine1** [comment]
I'm not seeing this behavior.  Do you have a scenario or particular case this happens in?

**Comment by CowboyCoderForever** [comment]
> I'm not seeing this behavior. Do you have a scenario or particular case this happens in?

I can't reproduce this anymore. Closing.
