### ISSUE TITLE
I want the component settings to look like the ui mockup

### ISSUE THREAD

**Issue by phfatmonkey** [mfthomps/CyberCIEGE-port-to-Unity3d#189]
Only on the settings that aren't purchased:

![image](https://user-images.githubusercontent.com/3812933/107063580-68226180-678f-11eb-978a-9f12c9fd14be.png)

should look more like this:

![image](https://user-images.githubusercontent.com/3812933/107063684-85573000-678f-11eb-9eff-dcfb71056b78.png)

**Comment by erheine1** [comment]
This is using the same logic as all the other policy lists.  If the policy has no cost then button's label is empty as above.  So make sure this doesn't break other policy list functionality.
