### ISSUE TITLE
Calculate security rating for zone

### ISSUE THREAD

**Issue by erheine1** [mfthomps/CyberCIEGE-port-to-Unity3d#194]
Look at the src code zone.cpp line 1486.  Will require adding security information to policies and some way to tell if a zone has a guard or not.

Probably requires some way to force user to hire guard before enabling policies that require a guard

**Comment by mfthomps** [comment]
This should come from the server?
enabling guard policies without hiring a guard is part of the game.

**Comment by erheine1** [comment]
If the server could calculate this and send a message to Unity when it changes, that would be easiest since it already has the logic for calculating it.
