### ISSUE TITLE
I don't want to see duplicate looking avatars in the same scenario.

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#227]
There are a variety of male/female worker prefabs to choose from.

I believe the OG just rotates through the available textures as each character gets created.

**Comment by mkrause-nps** [comment]
* [x] create multiple character _Users_ overrides for not yet configured prefabs (all based on parent _Character User_, which is based on _Character Base_)
* [x] create references in the those overrides (e.g., animation)
* [ ] modify ` ./Assets/Code/Scriptable Variables/AvatarPrefabMapping.cs` such that the _User_ characters look all different within one scene, but that each individual character always looks the same (when scene is played repeatedly) (e.g., pull them from a list always in the same order)
