### ISSUE TITLE
I want the characters to stop moving/animating when a dialog is opened

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#260]
When any dialog is open, the game is in a semi-frozen state (time stops ticking). The characters should stop walking and animating.

There are `AnimationFreezer` and `CharacterPauser` scripts which may be useful.

**Comment by erheine1** [comment]
Looks like the `AnimationFreezer` is on every character model prefab.  Is there a good way to get that component on the CharacterBase prefab and have it find the right Animator to control?  Otherwise, I have to put event listeners in a lot of different prefabs just to do the same thing.

**Comment by CowboyCoderForever** [comment]
> Looks like the `AnimationFreezer` is on every character model prefab. Is there a good way to get that component on the CharacterBase prefab and have it find the right Animator to control? Otherwise, I have to put event listeners in a lot of different prefabs just to do the same thing.

Hmm...I wasn't sure I wanted that Component to auto-find the Animator, in case there are multiple ones in the prefab. I suppose we could try your approach -- that would be one less thing to have to overwrite on every prefab...
