### ISSUE TITLE
[bug] Training->Stop Worms doesn't let the player answer the yes/no dialog before continuing as if the player selected No.

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#263]
* Play through the Training/Stop Worms scenario until you are prompted with a Yes/No question.
* Wait about 10 seconds, the next message box is displayed, indicating that you selected No.

**Comment by erheine1** [comment]
@mfthomps It looks to me like the message and confirmation dialogs are sending the dialog_up and dialog_closed messages correctly, but the scenario time doesn't pause when the confirmation dialog pops up.  Any idea why not?

**Comment by mfthomps** [comment]
It looks like scenario time is pausing as expected when dialogs come up.  However, when the question comes up, I do not see a dialog_up message.  I'm running the latest develop.
