### ISSUE TITLE
I want the Users to position themselves correctly when working at a computer

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#265]
The Users don't know anything about the chair or table and will sit down to work at the origin of the WorkSpace. Come up with some system to get them oriented and positioned correctly.

**Comment by CowboyCoderForever** [comment]
Roughly thinking:
- add a new Component (`Sitable`) to all prefabs that characters can sit on. This script could have a field indicating if someone is currently sitting there.
- Have the WorkSpace component know about any Sitables that have been added to it. The `WorkSpaceFactory` can do this when creating the WorkSpace.
- Then when the Users decide they can work (have been assigned a computer and a WorkSpace), they can find an available Sitable in the WorkSpace and nav to it.

**Comment by phfatmonkey** [comment]
Now that we're using the prefabs for each workspace, could the sitting location info be a part of them? I could create a transform built into the prefab that the character could move to.

**Comment by CowboyCoderForever** [comment]
> Now that we're using the prefabs for each workspace, could the sitting location info be a part of them? I could create a transform built into the prefab that the character could move to.

That's kind of what my rambling note above eludes to. I don't think we need a separate transform though; we can just "mark" the chair prefab with something that we can search for at runtime (a Component or Tag or something).
