### ISSUE TITLE
Implement Groups and Clearances dialogs/views

### ISSUE THREAD

**Issue by erheine1** [mfthomps/CyberCIEGE-port-to-Unity3d#298]
Accessible from the Game tab in the original, these dialogs let you view all the groups and clearances in a scenario, get their descriptions, and alter the background check level for a given group/clearance.

![image](https://user-images.githubusercontent.com/41123045/108898786-7d3f2300-75cc-11eb-820f-0e63252cacba.png)
![image](https://user-images.githubusercontent.com/41123045/108898745-70baca80-75cc-11eb-8f3f-14b7137cfee6.png)

**Comment by CowboyCoderForever** [comment]
...also available from the Asset Tab!

**Comment by erheine1** [comment]
Accessing it from the Assets tab was very unintuitive and confusing to me because the dialog lets you edit properties of clearances and groups completely independent of assets, so I don't know why you can even open it from that view.

**Comment by CowboyCoderForever** [comment]
> Accessing it from the Assets tab was very unintuitive and confusing to me because the dialog lets you edit properties of clearances and groups completely independent of assets, so I don't know why you can even open it from that view.

I agree. And the OG UI didn't make it look like it was even editable.
