### ISSUE TITLE
[bug] The displayed name of the Computers in the Components tab is different than OG

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#355]
The OG shows the computers based on their name (e.g. "Curly_ws"). Ours shows the name based on the hardware type (?).

Run the Introduction and purchase/assign a computer. Notice how the Components tab shows the name differently than the Original Game. Ditto with the Network tab.

![image](https://user-images.githubusercontent.com/7308321/109734575-12ff2300-7b76-11eb-840a-c3d9b91d5306.png)
![image](https://user-images.githubusercontent.com/7308321/109734593-1a263100-7b76-11eb-9e2e-4c3cf0d4935f.png)

**Comment by erheine1** [comment]
Fixed with the latest SimSecNoUI.exe
