### ISSUE TITLE
[refactor] Refactor the code to avoid needing the files in HardwareTypes

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#363]
There are several .txt files in this folder that are read at runtime. We can avoid the need to do this by copying the information contained in these files to ScriptableObjects and referencing these instead.

**Comment by erheine1** [comment]
I feel like #362 and #363 would be the exact same fix to cover both.

**Comment by CowboyCoderForever** [comment]
This looks like the [whole list of different hardware](https://gitlab.nps.edu/mfthomps/cyberciege/-/blob/master/ccsource/prog/game/hardware.cpp) available in the game:
