### ISSUE TITLE
Newly purchased equipment does not have the correct default policies enabled

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#37]
The Zone configuration scene contains a list of policies that are supposed to be applied on future purchased equipment. This doesn't seem to work.

To reproduce:
* In the Zone configuration screen, enable some of the policies (or all of them, if you like).
* Purchase a new PC and assign to a User.
* Right-click->Configure on that newly purchased PC to see its configuration.
* Notice its policies don't match the ones you set as default.

Note: This works in the original UI. Did this ever work in the Unity version?

**Comment by CowboyCoderForever** [comment]
It looks like the generated computer .sdf file that appears in the %appdata% folder has _some_ of the correct settings, but others are completely missing from the file.

My guess is the game server side isn't correctly configuring the newly purchased equipment, or at least, not including all of the configuration settings.

**Comment by erheine1** [comment]
Is this still the case?  It looks like it's working to me in the introductory scenario.

**Comment by CowboyCoderForever** [comment]
> Is this still the case? It looks like it's working to me in the introductory scenario.

Can't reproduce. Closing.
