### ISSUE TITLE
Implement Office View UI

### ISSUE THREAD

**Issue by erheine1** [mfthomps/CyberCIEGE-port-to-Unity3d#43]
Make a UI for the office view in game

**Comment by CowboyCoderForever** [comment]
Can you elaborate what this means? What should it look like?

**Comment by erheine1** [comment]
I guess the concept art doesn't have any of the camera control buttons.  I do think we'll need some buttons for those (like go to next user, next device, etc) like the Java version has.  Also, depending on how we're going to handle clicking on things in the scene, we might need a UI area to do that (basically a big empty area that you can see through, but catches mouse clicks so that if a dialog is popped up, you aren't secretly clicking on things in the scene.

**Comment by erheine1** [comment]
This functionality:
![image](https://user-images.githubusercontent.com/41123045/105519282-160d1680-5c8e-11eb-96bd-42de7da819ed.png)
