### ISSUE TITLE
As a Player, I want to know when the Attack Log has new logs added to it

### ISSUE THREAD

**Issue by CowboyCoderForever** [mfthomps/CyberCIEGE-port-to-Unity3d#85]
The player needs to have an indication the Attack log has new entries since the last time they looked at it.

Note, there is some existing functionality in the `AttackLogScript` that changes the look of the button when the attack log changes. This might be of use.

**Comment by CowboyCoderForever** [comment]
I have hooked up this functionality into the new button, but the `AttackLogButton` doesn't jive well with the current button styling.

**Comment by erheine1** [comment]
Finished in issue #172 (not sure why Ryan keeps making his own duplicate issues)
