### ISSUE TITLE
Implement Attack Log UI

### ISSUE THREAD

**Issue by erheine1** [mfthomps/CyberCIEGE-port-to-Unity3d#89]
- Make it look like other new UI
- Make it use the ViewType system so the proper signals get sent to the server without having to be a special case

**Comment by CowboyCoderForever** [comment]
Related to #85

**Comment by CowboyCoderForever** [comment]
Related to #95?

**Comment by erheine1** [comment]
Mostly.  The ViewType stuff is different, but I kind of want to handle that on a broader level in a different case
